language: node_js
node_js:
  - "4"
  - "5"
addons:
  firefox: "latest"
before_script:
  - npm install -g gulp coveralls
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gulp build
  - cat report/coverage/lcov/lcov.info | coveralls
